spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "BLoHny"
    url: jdbc:mysql://localhost:3306/board
    password: "ird1600215!"
  jpa:
    hibernate:
      ddl-auto: none
